# Generated by Django 2.0.4 on 2018-04-27 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56, unique=True, verbose_name='Category name')),
                ('path', models.CharField(max_length=1024, verbose_name='Path to node')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adjacency.Category', verbose_name='Father')),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
