# Generated by Django 2.0.4 on 2018-04-27 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adjacency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adjacency.Category', verbose_name='Father'),
        ),
    ]
